"""init

Revision ID: 5309cd142934
Revises: 
Create Date: 2026-03-24 19:43:24.749642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5309cd142934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=False),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('date_reparation', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reparations_numero_serie'), ['numero_serie'], unique=False)

    op.create_table('pieces_changees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparation_id', sa.Integer(), nullable=False),
    sa.Column('ref_piece', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reparation_id'], ['reparations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pieces_changees')
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reparations_numero_serie'))

    op.drop_table('reparations')
    # ### end Alembic commands ###
